services:
  postgres:
    image: postgres:16
    container_name: postgres
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db_name
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db_name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d monitoring"]
      interval: 4s
      timeout: 2s
      retries: 5
    networks:
      #db_net
      - redisnet

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 1s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - redisnet

  producer1:
    build:
      context: ..
      dockerfile: docker_files/producer.dockerfile
    container_name: redis_producer1
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_STREAM: "stream1"
      PYTHONUNBUFFERED: "1"
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f producer.py || exit 1"]
      interval: 2s
      timeout: 1s
      retries: 10
    #MOUNTING THE DATA FILE SO WHEN THE CONTAINER IS RESTARTED THE DATA FILE IS REFRESHED
    volumes:
      - type: bind
        source: ../generated_file_1.json
        target: /szakd/generated_file.json
      - type: bind
        source: ../producer.py
        target: /szakd/producer.py
    networks:
      - redisnet

  producer2:
    build:
      context: ..
      dockerfile: docker_files/producer.dockerfile
    container_name: redis_producer2
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_STREAM: "stream2"
      PYTHONUNBUFFERED: "1"
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f producer.py || exit 1"]
      interval: 2s
      timeout: 1s
      retries: 10
    #MOUNTING THE DATA FILE SO WHEN THE CONTAINER IS RESTARTED THE DATA FILE IS REFRESHED
    volumes:
      - type: bind
        source: ../generated_file_2.json
        target: /szakd/generated_file.json
      - type: bind
        source: ../producer.py
        target: /szakd/producer.py
    networks:
      - redisnet

  consumer:
    build:
      context: ..
      dockerfile: docker_files/consumer.dockerfile
    container_name: redis_consumer
    env_file:
        - consumer.env
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db_name
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_STREAM: "stream2"
      PYTHONUNBUFFERED: "1"
      #producer1:
        #USE service_healthy IF THE PRODUCER DOES NOT END AFTER SENDING THE DATA
        #USE service_completed_successfully IF THE PRODUCER ENDS AFTER SENDING THE DATA
      #  condition: service_completed_successfully
    #MOUNTING THE CONSUMER SO WHEN THE CONTAINER IS RESTARTED THE CHANGES ARE PICKED UP
    volumes:
      - type: bind
        source: ../data.json
        target: /szakd/data.json
      - type: bind
        source: ../consumer.py
        target: /szakd/consumer.py
    networks:
      - redisnet
      
  dashboard:
    build:
      context: ..
      dockerfile: docker_files/dashboard.dockerfile
    container_name: streamlit_dashboard
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    volumes:
      - type: bind
        source: ../dashboard.py
        target: /szakd/dashboard.py
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db_name
    depends_on:
      postgres:
      #TODO: DASHBOARD SHOULD BE ACTIVE EVEN IF THESE SERVICES ARE DOWN
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - redisnet

secrets:
  postgres_user:
    file: ../secrets/postgres_user.txt
  postgres_password:
    file: ../secrets/postgres_password.txt
  postgres_db_name:
    file: ../secrets/postgres_db_name.txt

volumes:
  redis_data:
  postgres_data:

networks:
  redisnet: